spring:
  application:
    name: msavaliadorcredito
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_CLIENT_ID}:${EUREKA_CLIENT_SECRET}@${EUREKA_HOST}:${EUREKA_PORT}/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: '*'

mq:
  queues:
    emissao-cartoes: emissao-cartoes

logging:
  file:
    name: ./logs/log-file.log
