spring:
  application:
    name: mscloudgateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # estamos localizando os ms
          lower-case-service-id: true # com caixa baixa
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_HOST}:${KEYCLOAK_PORT}/realms/${KEYCLOAK_REALM}

server:
  port: 8080



eureka:
  client:
    fetch-registry: true # busca os registros
    register-with-eureka: true # registra com eureka
    service-url:
      defaultZone: http://${EUREKA_CLIENT_ID}:${EUREKA_CLIENT_SECRET}@${EUREKA_HOST}:${EUREKA_PORT}/eureka
